### ISSUE TITLE
index.gtml GO! 버튼 위치/디자인 개선

### ISSUE THREAD

**Issue by EmjayAhn** [EmjayAhn/SPARK_chat#1]

**Comment by jeina7** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [index.gtml GO! 버튼 위치/디자인 개선](https://trello.com/c/yAPmAAab/1-indexgtml-go-%EB%B2%84%ED%8A%BC-%EC%9C%84%EC%B9%98-%EB%94%94%EC%9E%90%EC%9D%B8-%EA%B0%9C%EC%84%A0)
